# Generated by Django 5.1.1 on 2024-09-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
